nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmScopes:
  "beeclover":
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
    npmPublishRegistry: "https://npm.pkg.github.com"
