name: Publish Package
on:
  push:
    branches: [main]
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Add GiHub Package Token
        run: |
          echo "
          npmAuthIdent: \"Hansanghyeon:${{ secrets.TOKEN }}\"
          npmAuthToken: \"${{ secrets.TOKEN }}\"
          " >> .yarnrc.yml
      - run: yarn
      - run: yarn npm publish
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}